### ISSUE TITLE
Error in 'roles/gaieges.flexget-daemon/handlers/main.yml': line 2, column 3

### ISSUE THREAD

**Issue by robgmills** [gaieges/flexget-daemon#1]
## Steps to reproduce
1. Install playbook with `ansible-galaxy`: 
   
   ```
   ansible-galaxy install gaieges.flexget-daemon -p roles/`
   ```
2. Include role in playbook:
   
   ```
   ---
   - hosts: flexget
     become: yes
     roles:
       - role: gaieges.flexget-daemon
         flexget_password: myPassword
   ```
3.  Run playbook:
   
   ansible-playbook -i 192.168.50.3, -b -u vagrant -k flexget.yml
## The Error =O

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/Users/rmills/Code/rgm/ansible-playbooks/roles/gaieges.flexget-daemon/handlers/main.yml': line 4, column 3, but may be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> &dash; name: enable flexget service
> 
>   ^ here
> 
> The error appears to have been in '/Users/rmills/Code/rgm/ansible-playbooks/roles/gaieges.flexget-daemon/handlers/main.yml': line 4, column 3, but may be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> &dash; name: enable flexget service
> 
>   ^ here
