### ISSUE TITLE
Multi-line flexget_tasks configuration fails schema validation when setting web user password

### ISSUE THREAD

**Issue by robgmills** [gaieges/flexget-daemon#3]
I can't seem to figure out the correct way to provide a value for the `flexget_tasks` variable in my playbook.  All of the options seem to result in outputting a flat yaml structure that doesn't pass the schema validation step when setting the password for the WebUI user.

My "research" seems to indicate that there's a [limitation to Jiinja2 `to_yaml`](http://stackoverflow.com/questions/28963751/ansible-write-variables-into-yaml-file) that requires [passing it through a second `indent` filter or setting the indent property on the `to_yaml`/`to_nice_yaml` filter](http://stackoverflow.com/questions/34004171/printing-a-variable-value-indented-in-a-yaml-file-using-ansible).

_If you have a working example, can you provide one?_
## Error

```
RUNNING HANDLER [gaieges.flexget-daemon : set flexget web password] ************
fatal: [192.168.50.3]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/flexget", "-c", "/etc/flexget/config.yml", "web", "passwd", "mysecretpassword"], "delta": "0:00:02.298697", "end": "2016-09-13 19:23:00.992113", "failed": true, "rc": 1, "start": "2016-09-13 19:22:58.693416", "stderr": "Could not start manager: Did not pass schema validation.", "stdout": "2016-09-13 19:23 VERBOSE  manager                       Creating new database /etc/flexget/db-config.sqlite - DO NOT INTERUPT ...\n2016-09-13 19:23 CRITICAL manager                       [/tasks] Got `[{u'transmission': {u'host': u'localhost', u'port': 9091}, u'all_series': True, u'download-rss': None, u'rss': {u'url': u'http://some.com/rss.rss', u'all_entries': False}}]`, expected: dict\n2016-09-13 19:23 CRITICAL manager                       Failed to load config file: Did not pass schema validation.", "stdout_lines": ["2016-09-13 19:23 VERBOSE  manager                       Creating new database /etc/flexget/db-config.sqlite - DO NOT INTERUPT ...", "2016-09-13 19:23 CRITICAL manager                       [/tasks] Got `[{u'transmission': {u'host': u'localhost', u'port': 9091}, u'all_series': True, u'download-rss': None, u'rss': {u'url': u'http://some.com/rss.rss', u'all_entries': False}}]`, expected: dict", "2016-09-13 19:23 CRITICAL manager                       Failed to load config file: Did not pass schema validation."], "warnings": []}
```
### Straight Yaml (as in the example)

```
flexget_tasks:
  download-rss:
    rss:
      url: "{{ showrss_rss_feed }}"
      all_entries: no
    all_series: yes
    transmission:
      host: localhost
      port: 9091
```
### Multi-line literal string value

```
flexget_tasks: |
```
### Single line JSON

```
flexget_tasks: 
  download-rss: { rss: { url: "{{ showrss_rss_feed }}", all_entries: no }, all_series: yes, transmission: { host: localhost, port: 9091 } }
```
## Output in `/etc/flexget/config.yml`

In all cases, the output in the `config.yml` seemed to be flattened and didn't pass schema validation:

```
tasks:
  download-rss:
  all_series: true
  rss: {all_entries: false, url: 'http://some.com/rss.rss'}
  transmission: {host: localhost, port: 9091}
```

**Comment by gaieges** [comment]
Was the tasks stanza the only problem you had?  (ie you didn't have one with the schedules right?)  I think I have a different fix for this, one that's a bit cleaner I think, am curious if it works for you.  Will create a PR in a sec.  More focused on this as I'm guessing it's giving you more problems than the Vagrant thing for now :)

**Comment by gaieges** [comment]
Give that change a try - let me know if it works in your use case

**Comment by robgmills** [comment]
Yeah, I like that much better than using `indent`.  

Result looks good.  

## Input

```
flexget_schedules:
  - tasks: "download-rss"
    interval:
      minutes: 5
flexget_tasks:
  download-rss:
    rss:
      url: "http://some.com/rss.rss"
      all_entries: no
    all_series: yes
    transmission:
      host: localhost
      port: 9091
```

## Output

```
# write out schedules in proper format
schedules:
-   interval:
        minutes: 5
    tasks: download-rss


# write out tasks in proper format
tasks:
    download-rss:
        all_series: true
        rss:
            all_entries: false
            url: http://some.com/rss.rss
        transmission:
            host: localhost
            port: 9091
```
